ADD: 정거장, 택시기사, 이벤트 정보 제공 API 작성
wecode-bootcamp-korea/20-2nd-WattaTaxi-backend pull request #4
Opened 2021-05-30 21:48 UTC by 111geon

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 정거장, 택시기사, 이벤트 정보 제공 API 작성
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 아직 진행 중입니다.

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [x] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2021-05-31 10:17 UTC, Kang-kyunghun requested changes

2021-05-31 10:17 UTC, Kang-kyunghun commented on requirements.txt
> +urllib3==1.26.5
requirments.txt 파일 상태가 이상합니다. 확인 바랍니다.

2021-05-31 10:17 UTC, Kang-kyunghun commented on taxis/views.py
> +                        "review_count"          : DriverReview.objects.filter(taxi_driver=driver).count(),
이미 알고 있는 driver로부터 리뷰 카운트를 알 수 있을 것 같습니다.

2021-05-31 10:17 UTC, Kang-kyunghun commented on taxis/views.py
> +                        "average_rating"        : DriverReview.objects.filter(taxi_driver=driver).aggregate(average_rating=Coalesce(Avg('rating'), 0.0)).get('average_rating'),
이 부분도 위의 내용과 같이 이미 알고 있는 driver로부터 데이터를 가져와 보세요.

2021-05-31 10:17 UTC, Kang-kyunghun commented on taxis/views.py
> +
혹시 select_related와 prefetch_related도 적용할 수 있으면 적용해 보고 log 확인해서 적용이 잘 되었는지도 확인해 보세요.

2021-05-31 11:13 UTC, 111geon commented on requirements.txt
> +urllib3==1.26.5
수정하였습니다!

2021-05-31 11:13 UTC, 111geon commented on taxis/views.py
> +                        "review_count"          : DriverReview.objects.filter(taxi_driver=driver).count(),
_set을 이용하는 방식으로 수정하였습니다

2021-05-31 11:14 UTC, 111geon commented on taxis/views.py
> +                        "average_rating"        : DriverReview.objects.filter(taxi_driver=driver).aggregate(average_rating=Coalesce(Avg('rating'), 0.0)).get('average_rating'),
여기도 _set을 이용하여 수정하였습니다

2021-05-31 11:15 UTC, 111geon commented on taxis/views.py
> +
이 부분은 이해를 잘 못했습니다 추가적으로 말씀해주실 수 있나요?

2021-06-01 05:26 UTC, Kang-kyunghun requested changes

2021-06-01 05:26 UTC, Kang-kyunghun commented on taxis/views.py
> +
추가적으로 할 수 있으면 좋을 것 같아요!!

2021-06-01 05:26 UTC, Kang-kyunghun commented on taxis/views.py
> +                        "review_count"          : driver.driverreview_set.all().count(),
.all() 빼고도 되면 .all() 제거해 주세요.

2021-06-01 17:30 UTC, 111geon commented on taxis/views.py
> +                        "review_count"          : driver.driverreview_set.all().count(),
.all() 이 필요없었습니다. 필요 없는 부분들은 모두 제거해주었습니다.

2021-06-01 17:31 UTC, 111geon commented on taxis/views.py
> +
select_related와 prefetch_related 적용하여 수정하였습니다. 
SQL query log를 찍어서 확인해본 결과 20개 정도밖에 안되는 데이터임에도 불구하고 속도 차이가 10배 정도 차이가 나는 것을 확인할 수 있었습니다.
감사합니다.

2021-06-03 09:16 UTC, Kang-kyunghun commented
LGTM~~!!

2021-06-03 09:16 UTC, merged