ADD: User Signup/Signin with Email or Kakao
wecode-bootcamp-korea/20-2nd-WattaTaxi-backend pull request #5
Opened 2021-05-30 21:49 UTC by 111geon

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 이메일 또는 카카오로그인으로 회원가입 및 로그인하는 기능입니다
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 아직 작업 진행중입니다.

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [x] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2021-05-31 10:19 UTC, Kang-kyunghun commented
카카오 로그인과 회원가입은 합친다고 했으니 일단 일반 로그인 회원가입 부분만 PR 올려주시면 그것부터 merge 할께요

2021-05-31 10:20 UTC, Kang-kyunghun requested changes

2021-05-31 10:20 UTC, Kang-kyunghun commented on users/views.py
> +        return JsonResponse({'kakao_token': kakao_token}, status=200)
이 부분은 제거하고 올려 주세요.

2021-05-31 10:20 UTC, Kang-kyunghun commented on decorators.py
> +    return wrapper
이 부분도 아까 설명했듯이 필요없는 부분이겠죠?

2021-05-31 10:21 UTC, Kang-kyunghun commented
1. 카카오 로그인과 회원가입은 합친다고 했으니 일단 일반 로그인 회원가입 부분만 PR 올려주시면 그것부터 merge 할께요.
2. 유닛테스트도 추가하여 올려주세요.

2021-05-31 17:09 UTC, 111geon commented
카카오 로그인과 회원가입 합쳤습니다! 로그아웃 기능도 추가하였습니다. 유닛 테스트도 빠른 시일내로 추가하겠습니다.

2021-05-31 17:10 UTC, 111geon commented on users/views.py
> +        return JsonResponse({'kakao_token': kakao_token}, status=200)
넵 따로 다른 브랜치에 빼두었습니다.

2021-05-31 17:10 UTC, 111geon commented on decorators.py
> +    return wrapper
네 이부분은 따로 데코레이터로 분리하지 않고 뷰에 포함시켰습니다

2021-06-01 05:53 UTC, Kang-kyunghun requested changes

2021-06-01 05:53 UTC, Kang-kyunghun commented on users/views.py
> +                return JsonResponse({'message':'already_exists', 'email':email}, status=400)
```suggestion
            if not Validation.validate_email(self, email):
                return JsonResponse({'message':'invalid_email'}, status=400)
                
            if not Validation.validate_password(self, password):
                return JsonResponse({'message':'invalid_password'}, status=400)
                
            if not Validation.validate_name(self, name):
                return JsonResponse({'message':'invalid_name'}, status=400)
                
            if not Validation.validate_duplication(self, email):
                return JsonResponse({'message':'already_exists', 'email':email}, status=400)
```

2021-06-01 05:53 UTC, Kang-kyunghun commented on users/views.py
> +            return JsonResponse({'message': 'kakaotoken_required'}, status=401)
```suggestion
        kakao_refresh_token = json.loads(request.body).get("refresh_token", None)
        
        if not kakao_access_token or not kakao_refresh_token:
            return JsonResponse({'message': 'kakaotoken_required'}, status=401)
```

2021-06-01 05:53 UTC, Kang-kyunghun commented on users/views.py
> +            return JsonResponse({'message': 'login_again'}, status=401)
```suggestion
        if kakao_user_info.get("msg") == "this access token does not exist":
            return JsonResponse({'message': 'invalid_jwt'}, status=401)
        
        if kakao_user_info.get("msg") == "this access token is already expired":
            return JsonResponse({'message': 'login_again'}, status=401)
```

2021-06-01 05:53 UTC, Kang-kyunghun commented on users/views.py
> +
key error 날 수 있겠끔 해주세요.

2021-06-01 17:59 UTC, 111geon commented on users/views.py
> +                return JsonResponse({'message':'already_exists', 'email':email}, status=400)
수정 완료하였습니다.

2021-06-01 17:59 UTC, 111geon commented on users/views.py
> +            return JsonResponse({'message': 'kakaotoken_required'}, status=401)
수정 완료하였습니다.

2021-06-01 17:59 UTC, 111geon commented on users/views.py
> +            return JsonResponse({'message': 'login_again'}, status=401)
수정 완료하였습니다.

2021-06-01 18:00 UTC, 111geon commented on users/views.py
> +
try except 구문을 예외처리를 확인하기 쉽게 위코드 컨벤션에 맞게 수정하였습니다

2021-06-03 10:12 UTC, Kang-kyunghun commented
goood~~!!

2021-06-03 10:12 UTC, merged