ADD: 댓글 추가, 읽어들이기, 삭제 기능 추가
wecode-bootcamp-korea/20-2nd-WattaTaxi-backend pull request #6
Opened 2021-06-01 04:11 UTC by 111geon

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 댓글 추가, 읽어들이기, 삭제 기능의 가장 단순한 기능만을 구현하였습니다.
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [x] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2021-06-01 06:02 UTC, Kang-kyunghun requested changes

2021-06-01 06:02 UTC, Kang-kyunghun commented on taxis/views.py
> +            reviews = DriverReview.objects.filter(taxi_driver=driver)
역참조로 잘 가져와 보세요.

2021-06-01 06:02 UTC, Kang-kyunghun commented on taxis/views.py
> +                    )
```suggestion
            if not TaxiDriver.objects.filter(id=driver_id).exist():
                return JsonResponse({}, status=401)
                
            driver_review = DriverReview.objects.create(
                    taxi_driver_id = driver_id,
                    user        = user,
                    rating      = rating,
                    review      = text
                    )
```

2021-06-01 18:49 UTC, 111geon commented on taxis/views.py
> +            reviews = DriverReview.objects.filter(taxi_driver=driver)
리팩토링을 해보니 애초에 driver를 만들 필요가 없었어서 reviews를 만들 때 taxi_driver_id를 바로 사용하는 방식으로 수정하였습니다

2021-06-01 18:49 UTC, 111geon commented on taxis/views.py
> +                    )
수정하였습니다!

2021-06-02 02:11 UTC, Kang-kyunghun requested changes

2021-06-02 02:11 UTC, Kang-kyunghun commented on taxis/views.py
> +            user      = request.user
delete method는 body가 존재하지 않습니다. 따라서 review_id를 path parameter로 받으시는 것으로 수정 부탁 드립니다.

2021-06-02 05:23 UTC, 111geon commented on taxis/views.py
> +            user      = request.user
넵 GET메소드와 POST메소드의 driver_id는 query parameter로,
DELETE 메소드에서의 review_id는 path parameter로 전달하도록 수정하였습니다.

2021-06-03 10:44 UTC, Kang-kyunghun commented
LGTM~~!

2021-06-03 10:45 UTC, merged