ADD: 승차권 예약 생성, 삭제, 사용자 예약 읽어오기 기능 추가
wecode-bootcamp-korea/20-2nd-WattaTaxi-backend pull request #7
Opened 2021-06-02 01:25 UTC by 111geon

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 승차권을 예약하고, 취소하고, 현재 로그인한 사용자가 예약한 내역을 보여주는 기능
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- order에는 하나의 예약이 담겨있고, 그 order를 참조하는 schedule_order는 편도일때는 한개, 왕복일때는 두개가 있습니다.

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [ ] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2021-06-02 02:09 UTC, Kang-kyunghun requested changes

2021-06-02 02:09 UTC, Kang-kyunghun commented on orders/views.py
> +                    'departure_location'      : order.scheduleorder_set.all()[0].schedule.course.departure_location.name,
```suggestion
                    'departure_location'      : order.scheduleorder_set.first().schedule.course.departure_location.name,
```
[0]을 사용하게 되면 데이터가 없었을 때 index 에러가 나올 수 있습니다.

2021-06-02 02:09 UTC, Kang-kyunghun commented on orders/views.py
> +
불필요한 공백은 제거해 주세요.

2021-06-02 06:38 UTC, 111geon commented on orders/views.py
> +
제거 완료하였습니다.

2021-06-02 06:41 UTC, 111geon commented on orders/views.py
> +                    'departure_location'      : order.scheduleorder_set.all()[0].schedule.course.departure_location.name,
order가 있으면 schedule_order가 무조건 있어야하는 로직입니다.
그래도 혹시 모르니 IndexError 에러 예외처리 해놓도록 하겠습니다.
그냥 first()를 이용할 경우에 order에 대응하는 schedule_order가 없다면 None이 반환되고 None.schedule... 이 되어 오류가 발생할 것으로 생각됩니다.

2021-06-02 07:54 UTC, Kang-kyunghun commented
유닛테스트 기다릴게요

2021-06-03 11:48 UTC, Kang-kyunghun commented
고생 많으셨습니다.~~!!!

2021-06-03 11:48 UTC, merged